In [0]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [0]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

In [4]:
print('Dataset size: {}'.format(irisdata.shape))
print('Dataset (first 5 rows): \n {}'.format(irisdata.head()))
X = irisdata.drop('Class', axis=1)  
y = irisdata['Class']

# 80-20 train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

Dataset size: (150, 5)
Dataset (first 5 rows): 
    sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [0]:
# Polynomial Kernel
svclassifier = SVC(kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)

In [7]:
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[11  0  0]
 [ 0 10  0]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        10
 Iris-virginica       1.00      1.00      1.00         9

    avg / total       1.00      1.00      1.00        30



In [0]:
# Gaussian Kernel
svclassifier = SVC(kernel='rbf')  
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)   


In [9]:
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[11  0  0]
 [ 0 10  0]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        10
 Iris-virginica       1.00      1.00      1.00         9

    avg / total       1.00      1.00      1.00        30



In [0]:
# Sigmoid Kernel
svclassifier = SVC(kernel='sigmoid')  
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)  


In [11]:
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[ 0  0 11]
 [ 0  0 10]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        11
Iris-versicolor       0.00      0.00      0.00        10
 Iris-virginica       0.30      1.00      0.46         9

    avg / total       0.09      0.30      0.14        30



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
